### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by fonzerelly** [maadc/studienarbeit_gruppe1#23]
**User Story:** Als PO möchte ich nach jedem Sprint-Ende die gleiche UserExperience erfahren können, wie der User selbst um den Fortschritt zu bewerten. Daher soll das Pong-Spiel als WebSite gehostet werden können.
**Akzeptanzkriterien:** Der aktuelle Stand der Applikation kann jederzeit auf einen Webserver gespielt werden und ist dort auch per Link zu erreichen.
**Storypoints:** 2

**Comment by fonzerelly** [comment]
Eine Möglichkeit ihre Ergebnisse zu veröffentlichen, wäre indem Sie die sog. github-pages nutzen. Wenn Sie in einem git-Repository einen Branch namens "gh-pages" erstellen und diesen auf ihr zentrales Repo in Github pushen, dann ist der Inhalt dieser Seite unter
<username>.github.io/<repository-name>
mit einem Browser erreichbar.

Sie können aber auch gerne jedwede andere Form der Publikation wählen, die Ihnen zur Verfügung steht.

**Comment by maadc** [comment]
Projekt wird auf meinem Server gehostet und vor jedem Sprint-Ende auf die neuste Version aktuallisiert.
