### ISSUE TITLE
AnalyseStory: TechnikGrundlage bestimmen

### ISSUE THREAD

**Issue by fonzerelly** [maadc/studienarbeit_gruppe1#24]
Als Team-Mitglied muss ich wissen, basierend auf welcher Technlogie die Applikation umgesetzt werden soll:

### Akzeptanzkriterien:
* Eine Entscheidung für ein Framework
* Es ist klar, wie Tests geschrieben werden können.

### Storypoints: 3

**Comment by maadc** [comment]
Possible Techniken:
Elm
HTML Canvas

**Comment by maadc** [comment]
Vanilla (pures) JavaScript testbar mit [Jest](https://jestjs.io)

**Comment by maadc** [comment]
[Reddit-Post mit der Frage](https://www.reddit.com/r/learnjavascript/comments/czjakc/for_designing_an_online_browser_game_would_it_be/), wie Web-Animation am besten umsetzbar ist. (HTML Canvas, SVG oder HTML+CSS). Unser Spiel ist ja im Grunde nichts anderes. 

Antwort: 
canvas: you'll be able to setup layers for events the way real animators do, very useful and its also all setup to perform animations out of the box, each layer is a canvas that your running a separate animation on. Canvas' have a clear background so all the layers appear seamlessly to be a singular canvas to the observer. So for instance you would want one layer of background, one layer to represent clouds moving in the sky, and another layer for foreground character animation etc. Being able to break it up by layers is indescribably important for doing animations of any complexity.
svg:you'll need to create it externally and the animations will only run in a set loop with no dynamic interface unless you are actively writing and reloading the svg text file
html with css: you can do it but you'll be limited and you'll find the browser resources will start to be consumed as you get a high number of individual elements in motion. You will also have to be very careful with the css so the elements stay within the confines and do not cause other dom elements to shift or move around, everything has to be position absolute.
Conclusion: The canvas element is your friend for this one, it was designed explicitly for this purpose and will be the easiest to masterfully control with simplicity and eloquence.

**Comment by maadc** [comment]
Framework: [Phaser](https://www.phaser.io/learn)
Basiert auch auch HTML-Canvas. Ein Framework, dass speziell zur Spiel Erstellung gedacht ist. Ich erkenne Elemente aus Elm wieder. 

Doch auch hier wieder HTML-Canvas. Mir scheint, wir kommen nicht drum herum. 
Warum ein Framework verwenden, wenn wir unser Spiel auch komplett selbst schreiben können? -> besserer Lerneffekt.

**Comment by fonzerelly** [comment]
Ich bin noch nicht davon überzeugt, dass man den Canvas einfach so mit JEST testen kann. Der Canvans ist ein Teil vom DOM, der mit einer komplexen API kommt. Folgendes CodeBeispiel haben Sie sicher schon aus der Docu gesehen
```
const helloWorld = () => {
    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d");
    ctx.font = "30px Arial";
    ctx.strokeText("Hello World", 10, 50);
}

```
Wie würden Sie hierfür einen Test schreiben?
```
let document, strokeText
beforeEach(() => {
    strokeText = jasmineSpy
    document = {
      getElementById : () => {
         return {
            getContext: () => {
               strokeText
            }
         }
      }
    }
}

it('should render hello world', () => {
    helloWorld();
    expect(strokeText).toHaveBeenCalledWith('Hello World', 10,50');
});
```

Glauben Sie mir bei noch komplizierteren Beispielen macht das Monstermocking keinen Spaß mehr. Wenn Sie mit dem Canvas arbeiten wollen, brauchen Sie eine gute Idee, wie sie die Interaktion mit dem Canvas auf ein Minimum reduzieren. Sonst wird ihre Testabdeckung zu gering und Sie laufen hier bewust Gefahr, dass Fehler in dieser Transformationsschicht nicht abbilden können. Vielleicht finden Sie eine Mocking-Lib für den Canvas. Darüber ließe sich reden. Für normale Webseiten gibt es [jsdom](https://www.npmjs.com/package/jsdom).  Oder Sie schauen Sich nochmal [Karma](https://karma-runner.github.io/latest/index.html) genauer an.

Aber einfach so los zu legen und für den Canvas zu Programmieren und diesen Code zu testen, das wird so nix, fürchte ich.

**Comment by Lenareulein** [comment]
Vorschläge Frameworks für unser Spieleprojekt: 

**jQuery + Erweiterung jQuery UI**
-  erweiterbar durch zahlreiche Plug-ins
-  Animationen und Effekte

**Angular**
- gut für die Entwicklung von Single- Page- Webanwendungen 
- anstatt mit JavaScript wird mit Typscript programmiert
- dynamisches Laden

**Ember**
- clientseitiges JavaScript Framework
- gut für die Entwicklung von Single-Page-Webanwendungen
- gerendertes HTML Dokument wird immer automatisch aktualisiert

**Stage.js**
-  nicht so verbreitet
- 2D opensource Javascript Bibliothek
- DOM ähnliches Baumdatenmodell
- interne Renderzyklen 
- wird für Game Developement verwendet.

**Comment by lisa-th** [comment]
**Festlegung der TechnikGrundlage**
Grundgerüst ohne Framework - reines HTML, CSS und JavaScript
Testing über Framework (noch nicht festgelegt)
