### ISSUE TITLE
Farbgestaltung 

### ISSUE THREAD

**Issue by Lenareulein** [maadc/studienarbeit_gruppe1#26]
**User Story:** Als Programmierer möchte ich eine Farbpalette haben, an der ich mich orientieren kann.
**Voraussetzungen:**
**Akzeptanzkriterium:** Farbpalette ist vorhanden

User-Story: 1

**Comment by maadc** [comment]
Wunsch: Lime-Grün

**Comment by Lenareulein** [comment]
**Farbwerte:** 
weiß: #FFFFFB
schwarz:#000000
blau: #0C1345
dunkelrot:#410A13
rot:#F8090A
