### ISSUE TITLE
Geschwindigkeit anpassen

### ISSUE THREAD

**Issue by LuisRuckriegel** [maadc/studienarbeit_gruppe1#47]
**User-Story:** Als Spieler möchte ich, dass der Ball sich so bewegt, dass es nicht zu einfach ist, den Ball mit der Pong-Bar zu erreichen.

**Akzeptanzkriterium:** Geschwindigkeit von Ball und Pong Bars erlauben spannende Ballwechsel.

**Comment by maadc** [comment]
Geschwindigkeit steigt mit jedem Ballwechsel
